services:
  foodtools-db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5937:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    command: >
      postgres
      -c max_connections=2000
      -c shared_buffers=1GB
      -c default_transaction_isolation='read committed'
      -c idle_in_transaction_session_timeout=30000
      -c lock_timeout=10000
      -c statement_timeout=60000
      -c deadlock_timeout=10000
      -c max_locks_per_transaction=128

volumes:
  db_data:
